version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: abhijeet
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://abhijeet:yourpassword@postgres:5432/mydatabase

  # frontend:
  #   build: ./frontend
  #   container_name: frontend_container
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
